## Følgende variabler må eksistere for å bruke denne propertyfilen:
## - SRVPENSJON_USERNAME
## - SRVPENSJON_PASSWORD
## - OPENAM_SECRET

NAIS_NAMESPACE: 'q1'

eessi-pensjon-active-profiles: ${spring.profiles.active}

eessi-pensjon-institusjon: 'NO:NAVAT07'

#eux-rina-api_v1:
eessipen-eux-rina:
   url: 'https://eux-rina-api-q1.nais.preprod.local/cpi'

virksomhet.person.v3:
  endpointurl: 'https://wasapp-q1.adeo.no/tpsws/ws/Person/v3'

aktoerregister.api.v1:
  url: 'https://app-q1.adeo.no/aktoerregister/api/v1'

pensjonsinformasjon:
  url: 'https://wasapp-q1.adeo.no/pensjon-ws/api/pensjonsinformasjon/v1'

requestsamlpolicy:
  path: 'classpath:policy/requestSamlPolicyNoTransportBinding.xml'

srveessipensjon:
  username: '${SRVEESSIPENSJON_USERNAME}'
  password: '${SRVEESSIPENSJON_PASSWORD_Q}'

app:
  name: 'DEVELOP'
  version: '0.1'

security-token-service-token:
  url: 'https://security-token-service.nais.preprod.local/rest/v1/sts/token'

securityTokenService:
  url: 'https://sts-q4.preprod.local/SecurityTokenServiceProvider/'
  #  url: 'https://sts-q1.preprod.local/SecurityTokenServiceProvider/'

server:
  servlet:
    session:
      timeout:  '2m'
  port:         '8081'

no.nav.security.jwt:
  issuer.oidc:
    discoveryurl: 'https://isso-q.adeo.no:443/isso/oauth2/.well-known/openid-configuration'
    accepted_audience: 'localhost,eessi-fagmodul-localhost,eessi-fagmodul,freg-token-provider-q4,eessi-pensjon-frontend-api-q1,ida-q'
  issuer.servicebruker:
    discoveryurl: 'https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration'
    accepted_audience: 'preprod.local,srveessipensjon,srvpensjon'

http.proxy.parametername:

management:
  endpoints:
    enabled-by-default: 'true'
    jmx:
      exposure.include: '*'
    web:
      exposure.include: '*'
